-- MySQL Script generated by MySQL Workbench
-- Tue Nov 24 00:38:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Group_Project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Group_Project` ;

-- -----------------------------------------------------
-- Schema Group_Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Group_Project` DEFAULT CHARACTER SET utf8 ;
USE `Group_Project` ;

-- -----------------------------------------------------
-- Table `Group_Project`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`User` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Birth_Date` DATETIME(3) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Shipping_Address_Id` INT NULL,
  `Billing_Address_Id` INT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Genre` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Genre` (
  `Genre_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Genre_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Singer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Singer` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Singer` (
  `Singer_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Singer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Language` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Language` (
  `Language_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Language_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Album` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Album` (
  `Album_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Code` VARCHAR(10) NOT NULL,
  `Description` TEXT NOT NULL,
  `Release_Date` DATETIME(3) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Copies` INT UNSIGNED NOT NULL,
  `Language_Language_ID` INT NOT NULL,
  `Singer_Singer_ID` INT NOT NULL,
  `Genre_Genre_ID` INT NOT NULL,
  PRIMARY KEY (`Album_ID`),
  INDEX `fk_Album_Language1_idx` (`Language_Language_ID` ASC),
  INDEX `fk_Album_Singer1_idx` (`Singer_Singer_ID` ASC),
  INDEX `fk_Album_Genre1_idx` (`Genre_Genre_ID` ASC),
  CONSTRAINT `fk_Album_Language1`
    FOREIGN KEY (`Language_Language_ID`)
    REFERENCES `Group_Project`.`Language` (`Language_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_Singer1`
    FOREIGN KEY (`Singer_Singer_ID`)
    REFERENCES `Group_Project`.`Singer` (`Singer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_Genre1`
    FOREIGN KEY (`Genre_Genre_ID`)
    REFERENCES `Group_Project`.`Genre` (`Genre_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Song` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Song` (
  `Song_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Album_Album_ID` INT NOT NULL,
  PRIMARY KEY (`Song_ID`),
  INDEX `fk_Song_Album1_idx` (`Album_Album_ID` ASC),
  CONSTRAINT `fk_Song_Album1`
    FOREIGN KEY (`Album_Album_ID`)
    REFERENCES `Group_Project`.`Album` (`Album_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Order` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Order` (
  `Order_ID` INT NOT NULL AUTO_INCREMENT,
  `User_User_ID` INT NOT NULL,
  `Order_Date` DATETIME(3) NOT NULL,  
  `Ship_Date` DATETIME(3) NOT NULL,
  `Card_Type` VARCHAR(50) NOT NULL,
  `Card_Number` CHAR(16) NOT NULL,
  `Card_Expires` CHAR(7) NOT NULL,
  `Shipping_Address_Id` INT NOT NULL,
  `Billing_Address_Id` INT NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `fk_Orders_User1_idx` (`User_User_ID` ASC),
  CONSTRAINT `fk_Orders_User1`
    FOREIGN KEY (`User_User_ID`)
    REFERENCES `Group_Project`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Order_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Order_Item` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Order_Item` (
  `Order_Item_ID` INT NOT NULL AUTO_INCREMENT,
  `Order_Order_ID` INT NOT NULL,
  `Album_Album_ID` INT NOT NULL,
  `Item_Price` DECIMAL(10,2) NOT NULL,
  `Qty` INT(11) NOT NULL,
  PRIMARY KEY (`Order_Item_ID`),
  INDEX `fk_Order_Item_Album1_idx` (`Album_Album_ID` ASC),
  INDEX `fk_Order_Item_Order1_idx` (`Order_Order_ID` ASC),
  CONSTRAINT `fk_Order_Item_Album1`
    FOREIGN KEY (`Album_Album_ID`)
    REFERENCES `Group_Project`.`Album` (`Album_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Item_Order1`
    FOREIGN KEY (`Order_Order_ID`)
    REFERENCES `Group_Project`.`Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_Project`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group_Project`.`Address` ;

CREATE TABLE IF NOT EXISTS `Group_Project`.`Address` (
  `Address_Id` INT NOT NULL AUTO_INCREMENT,
  `User_User_ID` INT NOT NULL,
  `Line1` VARCHAR(45) NOT NULL,
  `Line2` VARCHAR(45) NULL,
  `City` VARCHAR(40) NOT NULL,
  `Province` VARCHAR(2) NOT NULL,
  `Country` VARCHAR(40) NOT NULL,
  `Phone` VARCHAR(12) NOT NULL,
  `Disabled` TINYINT(1) ZEROFILL NOT NULL,
  PRIMARY KEY (`Address_Id`),
  INDEX `fk_Address_User1_idx` (`User_User_ID` ASC),
  CONSTRAINT `fk_Address_User1`
    FOREIGN KEY (`User_User_ID`)
    REFERENCES `Group_Project`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
